---
title: About This Website
author: ''
date: '2020-12-30'
slug: about-this-website
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-12-30T16:21:33-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
draft: true
bibliography: [../../../static/bib/utexas.bib]
---

This website is a running commentary on my study and practice of a new discipline, called **Data Science**. I call this discipline **Applied Statistics** when speaking to my friends and family.

**Spring 2021 -- Let the games begin!** I decided over a year ago to study data science formally through an academic program. To that end, I applied to and was accepted to (thankfully) the [Master of Science in Data Science Online](http://ms-datascience.utexas.edu/) at the University of Texas at Austin. 

I am motivated to attend UT Austin for several reasons, including UT's commitment to a deep mathematical approach to applied statistics, not to mention my hometown attachment to UT Austin. To learn more about my decision, please see my first blog post on [Why I decided to attend the University of Texas at Austin](/post/why-i-decided-to-attend-the-university-of-texas-at-austin/).

**Isn't academia boring, long, expensive, and out-of-touch?** I fully agree that attending a formal program is long, expensive, and potentially out-of-touch. Nonetheless, I decided to take a formal approach that is rooted in mathematics, not in tools. I really want to understand the math with purpose, not with a glance -- I will decide on my own whether my study is too deep.  

As for academia vs industry, I value both equally: academic rigor gives me a firm understanding of 'why' and 'how' a solution exists; whereas, industry focus gives me a strong sense of purpose and application.

Ultimately, I decided to start my venture into data science formally. I want to go deep on the mathematics and statistics, and then learn the appropriate technologies along the way, not vice versa.

**So why not just read a bunch of books?** I know that I can learn data science through any combination of books. On [O'Reilly's Learning Platform](https://www.oreilly.com/) alone, I found nearly 4,000 books with "data science" relevant to their content. Similarly, I found by Google search many a page listing must-read books now: "50 Must-Read Free Books For Every Data Scientist in 2020" [@Verma2020]. 

For me, finding a book is not the problem -- it's knowing where to start that trips me up. That said, I plan to use my formal study as my primary path, and then use supplemental materials along the way.

**What about following your own prescribed curriculum?** I agree wholeheartedly: not only will I develop my *own* path along the way, I will also borrow from the advice of others on the same. In particular, I really like David Venturi's [@Venturi2016] planned curriculum. I couldn't agree more with Venturi's proposal to study what he wants to study, when he wants to study it, and how.

**Why not learn through a technology by doing, not by studying?** I guess so, but I wouldn't recommend it. I agree that learning through a particular technology grounds you quickly in an application, but doing so also biases you towards a particular train of thought: if all you have is a hammer, then everything looks like a nail. Technologies come and go, if not at least in favor or not. I believe that knowing both the why (mathematics, statistics) *and* the how (technology) is a better, more balanced approach.

**Don't you need a target industry or domain?** I do, but for now I am not targeting a particular industry or domain. I am going to see how that plays out as I go along.

**Taking the best from each world.** So there you have it. I plan to use my formal curriculum as my primary path of study, with plans to include suggestions from others on readings and technologies along the way. 

Malcolm

### References
