# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "/about"
  weight = 20

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Math"
  weight = 30

#[[main]]
#  name = "Courses"
#  url = "/courses"
#  weight = 31

[[main]]
  name = "Study"
  url = "/study"
  weight = 32

#[[main]]
#  name = "Demonstration"
#  url = "/demonstration"
#  weight = 42

#[[main]]
#  name = "Algebra 3"
#  url = "/algebra-3"
#  weight = 40

#[[main]]
#  name = "BCA"
#  url = "/bca"
#  weight = 50

#[[main]]
#  name = "Flashcards"
#  url = "/bca-flashcards"
#  parent = "BCA"
#  weight = 53

#[[main]]
#  name = "Linear Graphs"
#  url = "/bca-linear-graphs"
#  parent = "BCA"
#  weight = 54

#[[main]]
#  name = "Long Division"
#  url = "/bca-long-division"
#  parent = "BCA"
#  weight = 57

#[[main]]
#  name = "Rational Functions"
#  url = "/bca-rational-functions"
#  parent = "BCA"
#  weight = 56

#[[main]]
#  name = "Quadratics"
#  url = "/bca-quadratics"
#  parent = "BCA"
#  weight = 55

#[[main]]
#  name = "Binomials"
#  url = "/bca-binomials"
#  parent = "BCA"
#  weight = 57

#[[main]]
#  name = "Polynomials"
#  url = "/bca-polynomials"
#  parent = "BCA"
#  weight = 58

#[[main]]
#  name = "Questions"
#  url = "/bca-questions"
#  parent = "BCA"
#  weight = 59

#[[main]]
#  name = "Rotation of Solids"
#  url = "/bca-rotation-of-solids"
#  parent = "BCA"
#  weight = 60

#[[main]]
#  name = "Technology"
#  url = "/bca-technology"
#  parent = "BCA"
#  weight = 61

[[main]]
  name = "Combinatorics"
  url = "/tag/combinatorics"
  parent = "Math"
  weight = 1

#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

#[[main]]
#  name = "Tech"
#  url = "#tech"
#  weight = 42

#[[main]]
#  name = "Hugo"
#  url = "/hugo"
#  parent = "Tech"
#  weight = 53

#[[main]]
#  name = "Hugo-Academic"
#  url = "/hugo-academic"
#  parent = "Tech"
#  weight = 53

#[[main]]
#  name = "RStudio"
#  url = "/rstudio"
#  parent = "Tech"
#  weight = 54

#[[main]]
#  name = "Python Language"
#  url = "/python-language"
#  parent = "Tech"
#  weight = 55

#[[main]]
#  name = "R Language"
#  url = "/r-language"
#  parent = "Tech"
#  weight = 56

#[[main]]
#  name = "Statistics"
#  url = "#statistics"
#  weight = 43

#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

#[[main]]
#  name = "Tech"
#  url = "#tech"
#  weight = 42

#[[main]]
#  name = "Ed Tech"
#  url = "#edtech"
#  weight = 44

#[[main]]
#  name = "3D-Graphics"
#  parent = "Ed Tech"
#  url = "/3d-graphics"
#  weight = 44

#[[main]]
#  name = "2D-Graphics"
#  parent = "Ed Tech"
#  url = "#2d-graphics"
#  weight = 44

#[[main]]
#  name = "Negative Binomial Distribution"
#  url = "/negative-binomial-distribution"
#  parent = "Statistics"
#  weight = 56

#[[main]]
#  name = "Hypergeometric Distribution"
#  url = "/hypergeometric-distribution"
#  parent = "Statistics"
#  weight = 57

#[[main]]
#  name = "Misc Statistics"
#  url = "/misc-statistics"
#  parent = "Statistics"
#  weight = 58

#[[main]]
#  name = "More Math"
#  url = "/more-math"
#  weight = 58

#[[main]]
#  name = "Techniques of Integration"
#  url = "/techniques-of-integration"
#  parent = "More Math"
#  weight = 58

#[[main]]
#  name = "Power Series"
#  url = "/power-series"
#  parent = "More Math"
#  weight = 58

#[[main]]
#  name = "Binomial Coefficient Identities"
#  url = "/binomial-coefficient-identities"
#  parent = "More Math"
#  weight = 58

##########################################################
# These items were present in the beginning when I started
# working with Hugo-Academic
#
#[[main]]
#  name = "Talks"
#  url = "#talks"
#  weight = 40

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 50

#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 60

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
