theme = "starter-academic"
# Configuration of Hugo
# Guide: https://wowchemy.com/docs/get-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "railey.io"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://railey.io"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; M Railey {year}"

# Set my Google Analytics code
#
# Perhaps not needed .. googleAnalytics = "G-9S4XTF1TN0"

############################
## Advanced options below ##
############################

# Test Cookie Privacy Feature
privacy_pack = true

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

summaryLength = 30  # Listing summary length in words. Also, see `abstract_length` in `params.toml`.
paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
enableRobotsTXT = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

#"three", "stats.min", "dat.gui.min", "OrbitControls", "SceneUtils", "THREE.MeshLine", "ctns-math3d.newer"
#"https://cpgd.co/wp-content/plugins/ctns/js/dist/three.js",
#"https://cpgd.co/wp-content/plugins/ctns/js/dist/three-gui.js",
#"https://cpgd.co/wp-content/plugins/ctns/js/dist/three-sceneutils.js",
#"https://cpgd.co/wp-content/plugins/ctns/js/dist/three-orbitcontrols.js",
#"https://cpgd.co/wp-content/plugins/ctns/js/dist/three-stats.js",
[params]
  graphic_3d_hdr = [ 
  ] 
  graphic_3d_ftr = [ 
      "/js/three.js", 
      "/js/stats.min.js", 
      "/js/dat.gui.min.js", 
      "/js/OrbitControls.js", 
      "/js/SceneUtils.js", 
      "/js/THREE.MeshLine.js", 
      "/js/ctns-math3d.newer.js" 
  ]
  graphic_inc = [
    "/ctns/js/lib/katex/katex/katex.min.css",
    "/pm-math/includes/pm-math.css",
    "//cdn.jsdelivr.net/npm/jsxgraph@1.2.1/distrib/jsxgraph.css",
    "/css/pm-struct.css",
    "/css/dashicons.min.css",
  ]
  graphic_hdr = [
    #"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js",
    #"https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js",
    #"https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js",
    #"https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.4.0/backbone-min.js",
    "/js/ctns-scss.js",
    "/js/ctns-init.js",
    "https://cdnjs.cloudflare.com/ajax/libs/mathjs/6.1.0/math.min.js"
    #"https://cpgd.co/wp-content/plugins/ctns/js/lib/katex/katex/katex.min.js",
    #"https://cdnjs.cloudflare.com/ajax/libs/jsxgraph/0.99.7/jsxgraphcore.js",
    #"https://cpgd.co/wp-content/plugins/ctns/js/dist/three.js",
    #"https://cpgd.co/wp-content/plugins/ctns/js/dist/three-gui.js",
    #"https://cpgd.co/wp-content/plugins/ctns/js/dist/three-sceneutils.js",
    #"https://cpgd.co/wp-content/plugins/ctns/js/dist/three-orbitcontrols.js",
    #"https://cpgd.co/wp-content/plugins/ctns/js/dist/three-stats.js",
    #"https://cpgd.co/wp-content/plugins/ctns/js/dist/ctns-main-1-2.js",
    #"https://cpgd.co/wp-content/plugins/ctns/js/dist/ctns-main-2-1.js",
    #"https://cpgd.co/wp-content/plugins/ctns/js/dist/ctns-main-2-2.js",
    #"https://cpgd.co/wp-content/plugins/pm-struct/includes/pm-struct.js"
  ]
  graphic_ftr = [ 
    "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js",
    "https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.4.0/backbone-min.js",
    "/js/katex.min.js",
    "//cdn.jsdelivr.net/npm/jsxgraph@1.2.1/distrib/jsxgraphcore.js",
    "/js/jsxgraphcore-patch.js",
    "/js/ctns-main-1-2.js",
    "/js/ctns-main-2-1.js",
    "/js/ctns-main-2-2.js",
    "/js/pm-struct.js"
  ]

# Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular across Academic.
[permalinks]
  authors = "/author/:slug/"
  tags = "/tag/:slug/"
  categories = "/category/:slug/"
  publication_types = "/publication-type/:slug/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

# Configure the Markdown renderer.
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[imaging]
  resampleFilter = "lanczos"
  quality = 75
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

# Related content.
[related]
  threshold = 80.0
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "title"
    weight = 60.0

  [[related.indices]]
    name = "summary"
    weight = 50.0

  [[related.indices]]
    name = "tags"
    weight = 80.0

  [[related.indices]]
    name = "categories"
    weight = 70.0

  [[related.indices]]
    name = "authors"
    weight = 20.0

# Install Wowchemy
[module]
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy"
