---
title: Polynomials
author: ''
date: '2021-04-01'
slug: bca-fcs-polynomials
categories: []
tags: []
subtitle: ''
summary: ' '
authors: []
lastmod: '2021-04-01T16:39:30-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
type: book
graphic: true
math: true
jplayer: true
src_version: '704'
---
```{r setup, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
require(reticulate)
```

```{python, eval=TRUE, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
sys.path.append('../../../assets/python')

from ctns_make  import ctns_make  as CTNS_MAKE
from ctns_build import ctns_build as CTNS_BUILD
from ctns_flashcard_maker import flashcard_make as CTNS_FLASHCARD_MAKER
import ctns_form as CTNS

VERSION=704
```

```{python, eval=FALSE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
flashcard_data = [

    {'set_name': 'poly', 'name': 'gen_poly_binomial', 'filename': 'lib/gen_binomialS1', 'orig_filename': 'lib/binomialS1', 'front': 'Binomial', 'frontstyle': '', 'back': 'A <strong>binomial</strong> is a polynomial with two terms.', 'backstyle': 'width:70%;font-size:100%;', 'frontspeak': '', 'backspeak': ''}

  , {'set_name': 'poly', 'name': 'gen_poly_monomial', 'filename': 'lib/gen_monomialS1', 'orig_filename': 'lib/monomialS1', 'front': 'Monomial', 'frontstyle': '', 'back': 'A <strong>monomial</strong> is a polynomial with one term.', 'backstyle': 'width:70%;font-size:100%;', 'frontspeak': '', 'backspeak': ''}

  , {'set_name': 'poly', 'name': 'gen_poly_trinomial', 'filename': 'lib/gen_trinomialS1', 'orig_filename': 'lib/trinomialS1', 'front': 'Trinomial', 'frontstyle': '', 'back': 'A <strong>trinomial</strong> is a polynomial with three terms.', 'backstyle': 'width:70%;font-size:100%;', 'frontspeak': '', 'backspeak': ''}

  , {'set_name': 'poly', 'name': 'gen_poly_degree_of_a_polynomial', 'filename': 'lib/gen_polyDegS1', 'orig_filename': 'lib/polyDegS1', 'front': 'Degree of a Polynomial', 'frontstyle': '', 'back': 'The <strong>degree of a polynomial</strong> is the maximum number of variables that appear as factors in any one term.', 'backstyle': 'width:70%;font-size:100%;', 'frontspeak': '', 'backspeak': ''}

  , {'set_name': 'poly', 'name': 'gen_poly_polynomial_v1', 'filename': 'lib/gen_polyS1', 'orig_filename': 'lib/polyS1', 'front': 'Polynomial', 'frontstyle': '', 'back': 'A <strong>polynomial</strong> is an algebraic expression that involves only the operations of addition, subtraction, and multiplication of variables.', 'backstyle': 'width:70%;font-size:100%;', 'frontspeak': '', 'backspeak': ''}

  , {'set_name': 'poly', 'name': 'gen_poly_polynomial_v2', 'filename': 'lib/gen_polyS2', 'orig_filename': 'lib/polyS2', 'front': 'Polynomial', 'frontstyle': '', 'back': 'A <strong>polynomial</strong> is an algebraic expression that involves only the addition and subtraction of one or more terms.', 'backstyle': 'width:70%;font-size:100%;', 'frontspeak': '', 'backspeak': ''}

  , {'set_name': 'poly', 'name': 'gen_poly_degree_of_a_term', 'filename': 'lib/gen_polyTermDegS1', 'orig_filename': 'lib/polyTermDegS1', 'front': 'Degree of a Term', 'frontstyle': '', 'back': 'The <strong>degree of a term</strong> is the maximum number of variables that appear in that term.', 'backstyle': 'width:70%;font-size:100%;', 'frontspeak': '', 'backspeak': ''}

]

flashcard_list = CTNS_FLASHCARD_MAKER(flashcard_data);

print(flashcard_list)
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
flashcard_list = ['gen_poly_binomial', 'gen_poly_monomial', 'gen_poly_trinomial', 'gen_poly_degree_of_a_polynomial', 'gen_poly_polynomial_v1', 'gen_poly_polynomial_v2', 'gen_poly_degree_of_a_term']

#flashcard_list = ['gen_func_complex_numbers', 'gen_func_even_numbers']

flashcard_list = ['gen_poly_binomial']

m_list = [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_FLASHCARD_1 } for s in flashcard_list ]

q_list = [
    {'name': 'quiz_polynomials', 'options':CTNS.FORM_QUIZ_1 + ["count=%s" % len(flashcard_list)], 'qset': flashcard_list}
]
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
#print([m['name'] for m in m_list])
for m in m_list:
    CTNS_BUILD(target=m, process_support_files=True, version=VERSION, write_image=False, encrypt=False)
    #print("Built: %s" % m)
```

```{python, eval=FALSE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
#print([m['name'] for m in q_list])
for m in q_list:
    CTNS_BUILD(target=m, process_support_files=True, version=VERSION, write_image=False, encrypt=False)
```

```{r eval=TRUE, echo=FALSE}
blogdown::shortcode('quiz_polynomials')
```

----

```{r eval=TRUE, echo=FALSE}
blogdown::shortcode('gen_poly_binomial')
blogdown::shortcode('gen_poly_monomial')
blogdown::shortcode('gen_poly_trinomial')
blogdown::shortcode('gen_poly_degree_of_a_polynomial')
blogdown::shortcode('gen_poly_polynomial_v1')
blogdown::shortcode('gen_poly_polynomial_v2')
blogdown::shortcode('gen_poly_degree_of_a_term')
```
