---
title: Why I decided to pursue a degree in data science
author: ''
date: '2020-12-15'
slug: why-i-decided-to-pursue-a-degree-in-data-science
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-01-01T10:11:27-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
draft: false
bibliography: [../../../static/bib/utexas.bib]
---

So you want to be a data scientist? Sounds great! I want to be a data scientist, too. So then the question is, what is the best path to follow.

I decided that working towards a formal degree -- an online master's degree -- is the best approach. I do not doubt that everyone learns differently. And I recognize that not only everyone is starting from a different position, but also they are seeking a different end-goal. I should therefore clarify those points first as to the basis of my decision.

**Learning is different for everyone.** When I learn, I need a well-defined path with both a start and an end. When I read a book, for example, I read every damn page. However, I stop at many points to deep-dive into a question, a challenge, or a background detail. The path keeps me moving forward, while my deep-dive gives me depth and perspective. Yes, I am that person who stops to understand the proofs.

**Each of us benefits from different learning styles.** At the same time, it is essential to know what particular learning method works best for you. I learn first by reading and then second by doing. Reading allows me the time to absorb the material in-depth and note areas to revisit later. Unfortunately, I cannot rely on listening as my primary means to learn, which is why I require a companion text. Practice problems help, but not as much as a project.

**We have different starting points.** I already have a Ph.D. in Computer Science, which includes a strong mathematics background (though not a background in applied statistics). Understanding applied statistics, algorithms for machine learning, and data are my challenges, not writing code or learning new technology.

**Our end-goals are different.** As for my end-goal, I am leaving that choice open for now, albeit my options may range from research to consulting. I know that just as I am learning data science online, I plan to work in data science online.

**How I approach learning.** Knowing that I plan to listen to content, what I found works best for me is to read and understand the material first and then second use the lecturer's content to fill in the gap and provide emphasis. My approach implies I need access to written material (e.g., a textbook) for any course I take.

----

**Isn't academia boring, long, expensive, and out-of-touch?** I fully agree that attending a formal program is long, but that's the only point I agree with here. 

A master's program is time-consuming. But then I plan to hit the ground running from the start when I have useful information to work with for an internship or project. Ken Jee [@Jee2020] calls this having Minimum Viable Knowledge, which is to say, "you should understand just enough of these concepts [in data science] to be able to start exploring your ... projects."

Is a master's program expensive? Not really. Today's graduate programs are quite competitive: Georgia Tech is $11,706 out the door, University of Texas at Austin is a flat-fee of $10,000. Remember, too, that this cash outlay spans several years. In the meantime, I plan to capitalize on my investment early. 

As for whether an academic program is boring or out-of-touch, I believe that measure depends on me. A master's program is only as strong as I choose to make it.

**So why not just read a bunch of books?** I know that I can learn data science through any combination of books. On [O'Reilly's Learning Platform](https://www.oreilly.com/) alone, I found nearly 4,000 books with "data science" relevant to their content. Similarly, I found by Google search many a web page that lists today's must-read books: "50 Must-Read Free Books For Every Data Scientist in 2020" [@Verma2020]. 

For me, finding a book is not the problem -- knowing where to start is my problem. That said, I plan to use my formal study as my primary path and then use supplemental materials along the way.

**What about following a self-prescribed curriculum?** I agree wholeheartedly. Not only will I develop my *own* path along the way, but I will also borrow from others' advice on the same. In particular, I like David Venturi's [@Venturi2016] planned curriculum. I couldn't agree more with Venturi's proposal to study what he wants to learn, when he wants to understand it, and how.

Santiago Víquez Segura [Segura2020] suggests yet another proposal for self-study to include micro-courses by [Kaggle](https://www.kaggle.com/learn/overview). Segura's suggestions appear attractive and readily achievable, given each micro-course requires less than 4 hours to complete. 

I am confident that I will combine my academic work with these self-prescribed curriculums along with curriculum suggestions from others, including Sciforce [@Sciforce2019] and Paruchrui [@Paruchuri2020].

**Why not learn through technology by doing, not by studying?** I guess so, but I wouldn't recommend it. I agree that learning through a particular technology grounds you quickly in an application, but doing so also biases you towards one specific train of thought. If all you have is a hammer, then everything looks like a nail. Technologies come and go, if not at least fall into favor or out. Knowing both the why (mathematics, statistics) *and* the how (technology) is a better, more balanced approach.

**Don't you need a target industry or domain?** I do, but for now, I am not targeting a particular industry or field. I am going to see how that plays out as I go along.

**Which do you prefer, technology or theory.** Ultimately, I decided to start my venture into data science formally. I want to go deep on mathematics and statistics and then learn the appropriate technologies along the way, not vice versa.

### References
