---
title: BCA - Graphics - LinearQ2 - 2 thru 9
author: ''
date: '2021-03-24'
slug: bca-graphics-linearq2-2-thru-9
categories: []
tags: []
subtitle: ''
summary: ' '
authors: []
lastmod: '2021-03-24T14:22:19-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
graphic_3d: true
graphic: true
math: true
---
```{r setup, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
require(reticulate)
```

```{python, eval=TRUE, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
sys.path.append('../../../assets/python')

from ctns_make  import ctns_make as CTNS_MAKE
from ctns_build import ctns_build as CTNS_BUILD
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
m_list = [
    'linearQ2_1'
#    'linearQ2_2'
#    'linearQ2_3'
#    'linearQ2_4'
#    'linearQ2_5'
#    'linearQ2_6'
#    'linearQ2_7'
#    'linearQ2_8'
#  'linearQ2_9'
#   'linearQ2_A'
]

for m in m_list:
    CTNS_MAKE(match=m)
    CTNS_BUILD(match=m, process_support_files=False, id=m, image_target=m, opt_ctns = [ 
        "dynamic"
      , "qa"
      , "quiz_container_css='width:100%;'"
    ])
```

```{r eval=TRUE, echo=FALSE}
blogdown::shortcode('linearQ2_1')
blogdown::shortcode('linearQ2_2')
blogdown::shortcode('linearQ2_3')
blogdown::shortcode('linearQ2_4')
blogdown::shortcode('linearQ2_5')
blogdown::shortcode('linearQ2_6')
blogdown::shortcode('linearQ2_7')
blogdown::shortcode('linearQ2_8')
blogdown::shortcode('linearQ2_9')
blogdown::shortcode('linearQ2_A')
```
