---
title: Questions On Hugo-Academic
author: ''
date: '2020-12-20'
slug: questions-on-hugo-academic
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-12-20T08:19:33-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
draft: true
---

### Can I combine mark-up {{ }} with .Rmd files AND .md files? The context is that I need to execute {{ }} style instructions when I am inside an .Rmd file.

These are called Go Templates. So the question is whether I can run Go Templates from within documents for either R Markdown or Markdown syntax.


----

### Do these files NEED to be called index.this or index.that? 

My problem is that RStudio references these titles inside its editor by using the same name everywhere. All I see across the top is index.this and index.that.

----

### How do I designate a draft page?

I want to designate a draft page so that I can edit a page without posting the
same page for public consumption?

----

### HUGO: Check out, "hugo list XXX"

Separately, check out the expression, hugo list XXX, where XXX can be draft or future (whatever future means).

----

### Make note on how to change file names and slugs for posts on Hugo-Academic.

----

### How do I highlight text in-line?

Clearly, I need to be using highlight.js. I can't tell whether I should be using
highlight.js directly, through Hugo-Academic, or through Hugo. Of course, I 
couldn't find any references on this topic (either no one asked or no one knows). Then again, I see examples of in-line text highlighting throughout.

I will start again. Apparently, there is no particular method for changing the color of text in-line. The gross recommendation is to state specific HTML syntax, as in here is <span style="color: red;">some highlighted text</span>. For that matter, here is some other <span style="background-color:blue; color: red;">highlighted text</span>, which changes the color of a background, as well.

Check out https://medium.com/@codingdudecom/highlight-text-css-97331a5b71b5

<svg xmlns="//www.w3.org/2000/svg" version="1.1" class="svg-filters" style="display:none;">
  <defs>
    <filter id="marker-shape">
      <feTurbulence type="fractalNoise" baseFrequency="0 0.15" numOctaves="1" result="warp" />
      <feDisplacementMap xChannelSelector="R" yChannelSelector="G" scale="30" in="SourceGraphic" in2="warp" />
    </filter>
  </defs>
</svg>

These are great! Check out the Coding Dude at http://www.coding-dude.com/wp/css/highlight-text-css/.

Here are the assorted highlighter looks:

- <marker>default marker look</marker>
- <marker class='standard'>original marker look</marker>
- <marker class='ribbon'>ribbon marker look</marker>
- <marker class='arrow'>arrow marker</marker>
- <marker class='border-dash-red'>dashed red-line marker</marker>
- <marker class='sketch'>sketch marker</marker>
- <marker class='realistic'>realistic marker</marker>



