---
title: BCA - Dynamics - Rational Functions - D5
author: ''
date: '2021-04-02'
slug: bca-dynamics-rational-functions-d5
categories: []
tags: []
subtitle: ''
summary: ' '
authors: []
lastmod: '2021-04-02T15:31:37-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
math: true
type: book
graphic: true
jplayer: true
src_version: '419'
---
```{r setup, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
require(reticulate)
```

```{python, eval=TRUE, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
sys.path.append('../../../assets/python')

from ctns_make  import ctns_make  as CTNS_MAKE
from ctns_build import ctns_build as CTNS_BUILD
from ctns_flashcard_maker import flashcard_make as CTNS_FLASHCARD_MAKER
import ctns_form as CTNS

VERSION=419
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
slide_list = [
     "rational_functionD5_7"
  #  "rational_functionD5_1"
  #, "rational_functionD5_1a"
  #, "rational_functionD5_2"
  #, "rational_functionD5_2a"
  #, "rational_functionD5_3"
  #, "rational_functionD5_4"
  #, "rational_functionD5_5"
  #, "rational_functionD5_6"
  #, "rational_functionD5_6a"
  #, "rational_functionD5_7"
   , "rational_functionD5_8"
  #, "rational_functionD8_1"
]

m_list = [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_TEXT_1 } for s in slide_list ]
#print([m['name'] for m in m_list])

```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
for m in m_list:
    CTNS_BUILD(target=m, process_support_files=False, version=VERSION, write_image=False, encrypt=False)
    print("Built: %s" % m)
```

```{python, eval=FALSE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
for m in m_list:
    CTNS_MAKE(match=m)
    CTNS(match=m, opt_ctns = [ 
        "text"
      , "quiz_container_css='width:100%;'"
      , "quiz_css='width:100%;'"
      , "slide_css='width:100%;max-width:1024px;'"
      , "answer_css='font-size:1em;font-weight:normal;'"
      , "question_css='font-size:1em;font-weight:normal;'"
      , "css='text-align:left;font-family:helvetica;font-weight:normal;font-size:120%;color:rgb(77,77,77);'"
    ])
```

```{r eval=TRUE, echo=FALSE}
blogdown::shortcode('rational_functionD5_1')
blogdown::shortcode('rational_functionD5_1a')
blogdown::shortcode('rational_functionD5_2')
blogdown::shortcode('rational_functionD5_2a')
blogdown::shortcode('rational_functionD5_3')
blogdown::shortcode('rational_functionD5_4')
blogdown::shortcode('rational_functionD5_5')
blogdown::shortcode('rational_functionD5_6')
blogdown::shortcode('rational_functionD5_6a')
blogdown::shortcode('rational_functionD5_7')
blogdown::shortcode('rational_functionD5_8')
#blogdown::shortcode('rational_functionD8_1')
```
