---
title: Properties of Equality
author: ''
date: '2021-04-01'
slug: bca-fcs-properties-of-equality
categories: []
tags: []
subtitle: ''
summary: ' '
authors: []
lastmod: '2021-04-01T16:46:35-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
type: book
graphic: true
math: true
jplayer: true
---
```{r setup, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
require(reticulate)
```

```{python, eval=TRUE, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
sys.path.append('../../../assets/python')

from ctns_make  import ctns_make  as CTNS_MAKE
from ctns_build import ctns_build as CTNS_BUILD
from ctns_flashcard_maker import flashcard_make as CTNS_FLASHCARD_MAKER
import ctns_form as CTNS

VERSION=402
```

```{python, eval=FALSE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
flashcard_data = [

    {'set_name': 'prop_eq', 'name': 'gen_prop_eq_addition_property_of_zero_0', 'filename': 'lib/gen_prAddZeroS1', 'orig_filename': 'lib/prAddZeroS1', 'front': 'Addition Property of Zero (0)', 'frontstyle': '', 'back': 'For all real numbers $$x \\in \\mathbb{R},$$ $| x+0 = x. |$', 'backstyle': '', 'frontspeak': 'Addition Property of Zero', 'backspeak': 'For all real numbers X, -- the sum of X plus zero equals X.'}

  , {'set_name': 'prop_eq', 'name': 'gen_prop_eq_multiplication_property_of_one_1', 'filename': 'lib/gen_prMultOneS1', 'orig_filename': 'lib/prMultOneS1', 'front': 'Multiplication Property of One (1)', 'frontstyle': '', 'back': 'For all real numbers $$x \\in \\mathbb{R},$$ $|x \\cdot 1 = x.|$', 'backstyle': '', 'frontspeak': 'Multiplication Property of one', 'backspeak': 'For all real numbers X, -- the product of X times one equals X.'}

  , {'set_name': 'prop_eq', 'name': 'gen_prop_eq_multiplication_property_of_zero_0', 'filename': 'lib/gen_prMultZeroS1', 'orig_filename': 'lib/prMultZeroS1', 'front': 'Multiplication Property of Zero (0)', 'frontstyle': '', 'back': 'For all real numbers $$x \\in \\mathbb{R},$$ $|x \\cdot 0 = 0.|$', 'backstyle': '', 'frontspeak': 'Multiplication Property of zero', 'backspeak': 'For all real numbers X, -- the product of X times zero equals zero.'}

  , {'set_name': 'prop_eq', 'name': 'gen_prop_eq_reflexive_property_of_equality', 'filename': 'lib/gen_prReflexS1', 'orig_filename': 'lib/prReflexS1', 'front': 'Reflexive Property Of Equality', 'frontstyle': '', 'back': 'For all real numbers $$x \\in \\mathbb{R},$$ $|x = x.|$', 'backstyle': '', 'frontspeak': '', 'backspeak': 'For all real numbers X -- -- x -- equals -- x.'}

  , {'set_name': 'prop_eq', 'name': 'gen_prop_eq_substitution_property_of_equality', 'filename': 'lib/gen_prSubstS1', 'orig_filename': 'lib/prSubstS1', 'front': 'Substitution Property Of Equality', 'frontstyle': '', 'back': 'For all real numbers $$x,y \\in \\mathbb{R},$$<br/> if $$x=y$$, then $$y$$ can be substituted for<br/>$$x$$ in any expression.', 'backstyle': '', 'frontspeak': '', 'backspeak': 'For all real numbers X and Y, -- if x equals y -- then y can be substituted for x in any expression.'}

  , {'set_name': 'prop_eq', 'name': 'gen_prop_eq_symmetric_property_of_equality', 'filename': 'lib/gen_prSymmS1', 'orig_filename': 'lib/prSymmS1', 'front': 'Symmetric Property Of Equality', 'frontstyle': '', 'back': 'For all real numbers $$x,y \\in \\mathbb{R},$$<br/><br/>if $$x = y$$, then $$y = x.$$', 'backstyle': '', 'frontspeak': '', 'backspeak': 'For all real numbers X and Y -- if X equals Y -- then Y equals X.'}

  , {'set_name': 'prop_eq', 'name': 'gen_prop_eq_transitive_property_of_equality_transitive_property_of_order', 'filename': 'lib/gen_prTransS1', 'orig_filename': 'lib/prTransS1', 'front': 'Transitive Property Of Equality<br/> Transitive Property of Order', 'frontstyle': '', 'back': 'For all real numbers $$x,y,z \\in \\mathbb{R},$$<br/><br/>if $$x=y$$ and $$y=z$$, then $$x=z;$$ and, if $$x \\lt y$$ and $$y \\lt z$$, then $$x \\lt z.$$', 'backstyle': '', 'frontspeak': '', 'backspeak': ''}

  , {'set_name': 'prop_eq', 'name': 'gen_prop_eq_transitive_property_of_equality', 'filename': 'lib/gen_prTransS2', 'orig_filename': 'lib/prTransS2', 'front': 'Transitive Property Of Equality', 'frontstyle': '', 'back': 'For all real numbers $$x,y,z \\in \\mathbb{R},$$<br/><br/>if $$x=y$$ and $$y=z$$, then $$x=z.$$', 'backstyle': '', 'frontspeak': '', 'backspeak': 'For all real numbers -- X -- Y -- and Z -- if X equals Y -- and Y equals Zee, -- then X equals Zee.'}

  , {'set_name': 'prop_eq', 'name': 'gen_prop_eq_transitive_property_of_order', 'filename': 'lib/gen_prTransS3', 'orig_filename': 'lib/prTransS3', 'front': 'Transitive Property Of Order', 'frontstyle': '', 'back': 'For all real numbers $$x,y,z \\in \\mathbb{R},$$<br/><br/>if  $$x \\lt y$$ and $$y \\lt z$$, then $$x \\lt z.$$', 'backstyle': '', 'frontspeak': '', 'backspeak': 'For all real numbers X - Y - and Z -- if X is less than Y -- and Y is less than Z -- then X is less than Z.'}

  , {'set_name': 'prop_eq', 'name': 'gen_prop_eq_trichotomy', 'filename': 'lib/gen_prTrichS1', 'orig_filename': 'lib/prTrichS1', 'front': 'Trichotomy', 'frontstyle': '', 'back': 'For all real numbers $$x,y \\in \\mathbb{R},$$ exactly one of the following statements is true:<br/><br/> $$x \\lt y, \\ \\ x = y, \\ \\ x \\gt y$$', 'backstyle': '', 'frontspeak': '', 'backspeak': 'For all real numbers X and y, -- exactly one of the following statements is true -- x is less than y -- x is equal to y -- or -- x is greater than y.'}

  , {'set_name': 'prop_eq', 'name': 'gen_prop_eq_zero_product_rule', 'filename': 'lib/gen_prZeroProductRuleS1', 'orig_filename': 'lib/prZeroProductRuleS1', 'front': 'Zero Product Rule', 'frontstyle': '', 'back': 'For all real numbers $$x,y \\in \\mathbb{R},$$<br/> if $$ x \\cdot y = 0$$, then either $$x = 0$$ or $$y = 0.$$', 'backstyle': '', 'frontspeak': '', 'backspeak': 'For all real numbers X and Y, -- if the product of X times Y equals zero, -- then either x equals zero -- or y equals zero.'}

]

flashcard_list = CTNS_FLASHCARD_MAKER(flashcard_data);

print(flashcard_list)
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
flashcard_list = ['gen_prop_eq_addition_property_of_zero_0', 'gen_prop_eq_multiplication_property_of_one_1', 'gen_prop_eq_multiplication_property_of_zero_0', 'gen_prop_eq_reflexive_property_of_equality', 'gen_prop_eq_substitution_property_of_equality', 'gen_prop_eq_symmetric_property_of_equality', 'gen_prop_eq_transitive_property_of_equality_transitive_property_of_order', 'gen_prop_eq_transitive_property_of_equality', 'gen_prop_eq_transitive_property_of_order', 'gen_prop_eq_trichotomy', 'gen_prop_eq_zero_product_rule']

#flashcard_list = ['gen_func_complex_numbers', 'gen_func_even_numbers']

m_list = [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_FLASHCARD_1 } for s in flashcard_list ]

q_list = [
    {'name': 'quiz_prop_eq', 'options':CTNS.FORM_QUIZ_1 + ["count=%s" % len(flashcard_list)], 'qset': flashcard_list}
]
```

```{python, eval=FALSE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
#print([m['name'] for m in m_list])
for m in m_list:
    CTNS_BUILD(target=m, process_support_files=False, version=VERSION, write_image=True, encrypt=False)
    #print("Built: %s" % m)
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
#print([m['name'] for m in q_list])
for m in q_list:
    CTNS_BUILD(target=m, process_support_files=True, version=VERSION, write_image=False, encrypt=False)
```

```{r eval=TRUE, echo=FALSE}
blogdown::shortcode('quiz_prop_eq')
```

----

```{r eval=TRUE, echo=FALSE}
blogdown::shortcode('gen_prop_eq_addition_property_of_zero_0')
blogdown::shortcode('gen_prop_eq_multiplication_property_of_one_1')
blogdown::shortcode('gen_prop_eq_multiplication_property_of_zero_0')
blogdown::shortcode('gen_prop_eq_reflexive_property_of_equality')
blogdown::shortcode('gen_prop_eq_substitution_property_of_equality')
blogdown::shortcode('gen_prop_eq_symmetric_property_of_equality')
blogdown::shortcode('gen_prop_eq_transitive_property_of_equality_transitive_property_of_order')
blogdown::shortcode('gen_prop_eq_transitive_property_of_equality')
blogdown::shortcode('gen_prop_eq_transitive_property_of_order')
blogdown::shortcode('gen_prop_eq_trichotomy')
blogdown::shortcode('gen_prop_eq_zero_product_rule')
```
