---
title: Old Notes -- why I want to be a data scientist
author: ''
date: '2021-01-02'
slug: old-notes-why-i-want-to-be-a-data-scientist
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-01-02T10:26:48-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
draft: true
---

For some time, I have been writing software that helps kids learn math. Recently, I decided I need a change of venue: I like the challenge of software engineering; but, I need a different path. 

I need to work on more difficult problems in math and computer science; I want to use new programming languages, tools, and frameworks; and, I want to work with a variety of domains.

I believe working in data science will give me with that new sense of direction. Plus, doing so will satisfy my work requirements more broadly:

- Work remotely
- Work in software engineering
- Work in new areas in computer science
- Work in a domain with boundless opportunity
- Work in a domain that mathematically interesting
- Work in a domain with technical challenges

**Work remotely.**  Honestly, I don't want to move. Sure, I can work locally, but that would be limiting. Instead, I want to work remotely for whichever company from wherever I choose. Working remotely is not a limiting choice nowadays. 

**Work in software engineering.** I like software engineering, from writing code to designing new architectures. I just need more challenging problems, from working with complexity and uncertainty to solving problems of scale and design. And, I need more math. 

**Work in new areas in computer science. ** I am ready to give artificial intelligence a try. I want to solve problems across the board: robotics, vision, natural language processing, planning, machine learning, deep learning, and so forth. Clearly, I can combine this new path with my experience in software engineering.

I also want to expand into data -- lots of data. I am speaking about designing structures, writing algorithms, analyzing complexity, and working with architectures for scale and performance. 

**Work in a domain with boundless opportunity.** When I was a consultant, I always told myself, "there is always room for one in the movie theater." What I mean here is that I don't need work for 20 engineers, I only need work for one (me). 

Then again, securing even one seat as a software engineer is hard: you need to write a lot of code. On the other hand, securing a seat as a data scientist could be easy (no production code required): you need a path to a solid recommendation. 

Finding the path, not writing the code is the difference. And, as for finding that path, the sky is the limit.

**Work in a domain that is mathematically interesting.** I like the idea of adding complex math -- applied statistics -- to my work results. To that end, I am motivated to learn everything I can about applied statistics, machine learning, and deep learning, and then using today's technology to build upon that knowledge. I find it interesting that old topics in statistics are now considered fresh and innovative thanks to advances in technology.

**Work in a domain with technical challenges.** Here, I can leverage my past interest in fault tolerance, performance, and scale. Considering the size of the data to which we have access today, it is not surpise that solutions are measured the degree to which they scale. Not just any algorithm will do. I like this kind of a problem. Plus, there are many new (new to me) technologies that support deploying to distributed systems at scale.

In summary, I like the boundless opportunities to work on complex problems that leverages my past experience, yet offers me a new discipline for study. Clearly, data science serves to benefit everyone. So, to that end, carrying out work in data science gives me a good feeling.

----

Notice that in none of my assessment did I mention anything about the data itself:

-- I like working with data
-- I like presenting ideas through data
-- I like developing a persuasive argument through data

And so forth. In other words, the need to work with data is not my motivation. The concept of data is new to me. Therefore, working with data is new opportunity that I had not considered in the past.

----

I like begin told that the role I am working to fulfill is a sexy job. In their article for Harvard Business Review [@Davenport2012], Davenport and Patil describe the data scientist as just that: "Data Scientist: The Sexiest Job of the 21st Century." What I find interesting about their assessment is one of their examples regarding LinkedIn and Jonathon Goldman. The example they present speaks to the beginnings of LinkedIn at the point when someone -- Jonathon Goldman -- recognized the potential for identifying the social connections between people. So while LinkedIn engineering team focused on scaling up the technology, Goldman recognized the implied social networking amongst LinkedIn's users. "People You May Know," was Goldman's brainchild to start.

Had I been just working with LinkedIn engineering team, focused on making the architecture scale, I would have missed the opportunity hidden in the data itself. My point here archs back to my criterion for **Work in a domain with boundless opportunity.** 

As a practicing computer scientist with a specialty in software engineering, I can assure you there are great financial if not intellectual benefits from working in an area considered in the Top Five Jobs over the last 30 years.

https://www.glassdoor.com/research/best-jobs-in-america-for-2020/#
1/2 are directly related to software engineering for 2020

https://money.cnn.com/magazines/moneymag/bestjobs/2010/full_list/index.html
Software Architect has the top spot with a 34% expected job growth through the decade.

https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm

https://smartasset.com/retirement/the-rise-of-the-software-engineer

https://decideconsulting.com/software-developer-jobs-may-double-10-years/#:~:text=The%20Bureau%20of%20Labor%20Statistics,development%20jobs%20in%20the%20US.&text=In%20other%20words%2C%20the%20conservative,development%20jobs%20in%2010%20years.

https://www.bls.gov/opub/btn/volume-2/careers-in-growing-field-of-information-technology-services.htm

https://www.bls.gov/news.release/history/ecopro_12032001.txt

https://insights.dice.com/2020/01/27/software-developer-best-job-america/

https://money.usnews.com/careers/best-jobs/rankings/the-100-best-jobs

https://money.cnn.com/magazines/moneymag/bestjobs/2010/full_list/

https://www.cnbc.com/2010/01/06/The-Ten-Best-Jobs-in-America-2010.html

https://www.chicagotribune.com/news/ct-xpm-1994-06-01-9406010177-story.html

https://files.eric.ed.gov/fulltext/ED412360.pdf


There are certainly many avenues to learn and practice the art of data science.

https://www.businessofbusiness.com/articles/massive-increase-in-demand-for-data-science-jobs-in-2019/

https://www.forbes.com/sites/louiscolumbus/2017/05/13/ibm-predicts-demand-for-data-scientists-will-soar-28-by-2020/?sh=168cbd277e3b

https://2021.ai/data-science-landscape/

https://towardsdatascience.com/how-i-would-learn-data-science-if-i-had-to-start-over-f3bf0d27ca87

https://www.kdnuggets.com/2019/10/good-data-scientist-beginner-guide.html

https://www.dataquest.io/blog/learn-data-science/

https://towardsdatascience.com/was-my-data-science-masters-degree-worth-it-6b524dd35b33
