---
title: 1.3 Basic Properties of Algebra
author: ''
date: '2021-06-07'
slug: 1-3-basic-properties-of-algebra
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-06-07T09:45:44-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
math: true
type: book
graphic: true
jplayer: true
src_version: '215'
---
```{r setup, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
require(reticulate)
```

```{python, eval=TRUE, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
sys.path.append('../../../assets/python')

from ctns_make  import ctns_make  as CTNS_MAKE
from ctns_build import ctns_build as CTNS_BUILD
import ctns_form as CTNS

VERSION=215
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
slide_list = [
    'prZeroProductRuleS1'
]

m_list = [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_FLASHCARD_1 } for s in slide_list ]

q_list = [
    {'name': 'quiz_basic_axioms', 'options':CTNS.FORM_QUIZ_1 + ["count=10"], 'qset': slide_list}
]
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
for m in m_list:
    CTNS_BUILD(target=m, process_support_files=False, version=VERSION, write_image=False, encrypt=False)
```

```{python, eval=FALSE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
for m in q_list:
    CTNS_BUILD(target=m, process_support_files=False, version=VERSION, write_image=False, encrypt=False)
```

```{r eval=FALSE, echo=FALSE}
blogdown::shortcode('quiz_basic_axioms')
```

The following basic properties of algebra can be derived from the axioms of algebra.

- Zero Product Rule

```{r eval=TRUE, echo=FALSE}
blogdown::shortcode('prZeroProductRuleS1')
```
