---
title: Change of course. Literally.
author: ''
date: '2021-02-12'
slug: change-of-course-literally
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-02-12T13:34:43-05:00'
featured: no
image:
  placement: 1
  caption: '[A Green Heron At Merritt Island](https://www.audubon.org/field-guide/bird/green-heron) by C Railey is licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)'
  focal_point: ''
  preview_only: no
  alt_text: 'A Green Heron At Merritt Island'
projects: []
bibliography: ["../../../static/bib/library.bib"]
---
After three weeks of attending my first course on **Probability and Inference** [@Texas2021a] at the University of Texas at Austin, I decided I was not prepared for success and chose to drop the course rather than score poorly and suffer from anxiety all the while. Not surprisingly, my unexpected stress impacts my health, so I need (not just want) to drop the class.

Unfortunately, I didn't realize that dropping my (only) class equates to withdrawing from the university. Ouch! According to the university [@Texas2021],  

> If you wish to drop all of your courses after the semester begins, you must withdraw entirely from the university. 

That university rule applies to me since I was taking only one class from the start. Nonetheless, and despite the significance of the university's requirement, I still need to drop my class:

- **I failed to prepare for the course** because I misjudged the topic, and now as a result
- **I am overwhelmed by anxiety**, which I usually mitigate through intense preparation in the first place.  

To mitigate my course anxiety, I prepare for a course by reading the required textbook in advance, every page, every word. When I read a technical book, I don't let any concept skip by. I even read the captions in the figures (Who does that? Really?).

Unfortunately, in preparation for **Probability and Inference** [@Texas2021a], I read the wrong textbook(s) in advance. I read texts required by other universities for their classes on probability and statistics. Had I known the title of the required book, which ultimately implies the curriculum, I would have easily prepared for the course. 

Still, it is **my mistake** for not asking for the required textbook's name for my course. Despite my err, I completely understand why the professors chose their desired text. Their selected text is well-received in the community and covers an important topic directly inline with data science and machine learning -- I agree with the professor's choice.

----

Without going into details, I will offer a metaphor that illustrates how I misjudged the topic. What if, instead of attending an academic class, I was attending a week-long demanding tri-athlete camp that declares the following expectations:

- Learn how to warm up,
- Learn how to plan your race,
- Learn how to create a 3-month training plan,
- Learn how to "win" from the start of the race, and
- Learn how to persevere to the very end.

Given the tri-camp has never been run before, I can only assume the tri-camp (by name) is similar to other long-standing tri-camps: lots of running, some swimming, no cycling. In preparation for the tri-camp, I pace myself for months **running** the distances as chronicled by other tri-camps.

When I arrive, I realize the tri-camp focus is on swimming, not on running.  As I get off the bus upon arrival, I see everyone has brought their swim gear, and no one has brought any running gear. Oh no, did I sign up for the wrong (tri-camp) camp?

----

For now, I am changing course, literally. I will describe my new plan (strategy) in my next post. I hope my readers, including my family and friends, understand why I have changed course.

Although I have not changed my goal, I am still heading to Data Science Utopia. Only now, I am going to Utopia by land, not by sea.

### References
