---
title: BCA - Factoring
author: ''
date: '2021-06-18'
slug: bca-factoring
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-06-18T20:31:13-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
math: true
type: book
graphic: true
jplayer: true
src_version: '543'
---
```{r setup, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
require(reticulate)
```

```{python, eval=TRUE, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
sys.path.append('../../../assets/python')

from ctns_make  import ctns_make  as CTNS_MAKE
from ctns_build import ctns_build as CTNS_BUILD
from ctns_flashcard_maker import flashcard_make as CTNS_FLASHCARD_MAKER
import ctns_form as CTNS

VERSION=543
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
slide_list = [
     "rational_functionD8_4a"
   , "rational_functionD8_4b"
   , "rational_functionD8_4c"
   , "rational_functionD8_4d"
#    "rational_functionD8_2"
#  , "rational_functionD8_3"
#  , "rational_functionD8_4"
]

m_list = \
   [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_TEXT_1+['body_class="ctns-td-no-border ctns-no-color-group-message"', 'color_group_a'] } for s in ['rational_functionD8_4a'] ] \
 + [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_TEXT_1+['body_class="ctns-td-no-border ctns-no-color-group-message"', 'color_group_b'] } for s in ['rational_functionD8_4b'] ] \
 + [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_TEXT_1+['body_class="ctns-td-no-border ctns-no-color-group-message"', 'color_group_c'] } for s in ['rational_functionD8_4c'] ] \
 + [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_TEXT_1+['body_class="ctns-td-no-border ctns-no-color-group-message"', 'color_group_d'] } for s in ['rational_functionD8_4d'] ] \
# + [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_TEXT_1+['body_class="ctns-no-color-group-message"', 'color_group_a', 'color_group_b', 'color_group_c', 'color_group_d'] } for s in ['rational_functionD8_4']  ]

#m_list = \
#   [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_TEXT_1+['body_class="ctns-no-color-group-message"', 'color_group_a', 'color_group_b', 'color_group_c', 'color_group_d'] } for s in ['rational_functionD8_4']  ]

#q_list = [
#    {'name': 'quiz_abs_value_properties', 'options':CTNS.FORM_QUIZ_1 + ["count=14"], 'qset': slide_list}
#]
```

```{python, eval=FALSE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
slide_list = [
    'trinomialD1_1'
  , 'trinomialD1_1a'
  , 'trinomialD1_2'
  , 'trinomialD1_2a'
  , 'monomialD1_1'
  , 'monomialD1_1a'
  , 'exp1'
  , 'exp2'
  , 'exp3'
  , 'exp4'
  , 'exp5'
]

m_list = [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_SLIDE_1 } for s in slide_list ]

#q_list = [
#    {'name': 'quiz_abs_value_properties', 'options':CTNS.FORM_QUIZ_1 + ["count=14"], 'qset': slide_list}
#]
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
for m in m_list:
    CTNS_BUILD(target=m, preview=False, process_support_files=True, version=VERSION, write_image=False, encrypt=False)
    #print("Built: %s" % m)
```

```{python, eval=FALSE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
for m in m_list:
    CTNS_MAKE(match=m)
    CTNS(match=m, opt_ctns = [ 
        "text"
      , "quiz_container_css='width:100%;'"
      , "quiz_css='width:100%;'"
      , "slide_css='width:100%;max-width:1024px;'"
      , "answer_css='font-size:1em;font-weight:normal;'"
      , "question_css='font-size:1em;font-weight:normal;'"
      , "css='text-align:left;font-family:helvetica;font-weight:normal;font-size:120%;color:rgb(77,77,77);'"
    ])
```

```{r eval=TRUE, echo=FALSE}
#blogdown::shortcode('rational_functionD8_2')
#blogdown::shortcode('rational_functionD8_3')
#blogdown::shortcode('rational_functionD8_4')

blogdown::shortcode('rational_functionD8_4a')
blogdown::shortcode('rational_functionD8_4b')
blogdown::shortcode('rational_functionD8_4c')
blogdown::shortcode('rational_functionD8_4d')

#blogdown::shortcode('rational_functionD8_4')
```

```{r eval=FALSE, echo=FALSE}
blogdown::shortcode('trinomialD1_1')
blogdown::shortcode('trinomialD1_1a')
blogdown::shortcode('trinomialD1_2')
blogdown::shortcode('trinomialD1_2a')
blogdown::shortcode('monomialD1_1')
blogdown::shortcode('monomialD1_1a')
blogdown::shortcode('exp1')
blogdown::shortcode('exp2')
blogdown::shortcode('exp3')
blogdown::shortcode('exp4')
blogdown::shortcode('exp5')
```
