---
title: Derive Mean for Negative Binomial PMF for Y
author: ''
date: '2020-12-27'
slug: derive-mean-for-negative-binomial-pmf-for-y
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-12-27T14:10:58-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
math: true
---

In this post, we derive the mean value of the negative binomial probability mass function for random variable $Y$. 

If $Y$ is a random variable with a negative binomial probability distribution, then its probability mass function is given by the expression,

\begin{equation}
P(Y=y) = p(y) = {y-1 \choose r-1 } p^r(1-p)^{y-r}.
(\#eq:pmf)
\end{equation}

We note that if we sum the <strong>pmf</strong>, <strong>Eq.</strong> \@ref(eq:pmf), for values of $y \ge r$, then the result totals to the value 1, as expected for a <strong>pmf</strong>.

\begin{equation}
\sum^{\infty}_{y=r} {y-1 \choose r-1 } p^r(1-p)^{y-r} = 1.
(\#eq:one)
\end{equation}

The expected value $\mathbb{E}[X]$ is defined as follows,

\begin{align}
\mathbb{E}[Y] = & \sum^{\infty}_{y=r} y \cdot p(y) \\\\
              = & \sum^{\infty}_{y=r} y \cdot {y-1 \choose r-1 } p^r(1-p)^{y-r}.
(\#eq:mean)
\end{align}

From <strong>Eq.</strong> \@ref(eq:mean), our goal is to re-shape the summation so that it takes a form equivalent to <strong>Eq.</strong> \@ref(eq:one).

----

We begin with our definition (repeated here) of the expected value from <strong>Eq.</strong> \@ref(eq:mean),

\begin{equation}
\mathbb{E}[Y] = \sum^{\infty}_{y=r} y\cdot {y-1 \choose r-1 } p^r(1-p)^{y-r}.
(\#eq:expvalue)
\end{equation}

First, we expand our combination, 

\begin{equation}
\mathbb{E}[Y] = \sum^{\infty}_{y=r} y \cdot {\color{red} \frac{(y-1)!}{(r-1)! (y-r)!} } p^r(1-p)^{y-r}.
\end{equation}

From here, the leading $y$ combines with the factorial $(y-1)!$ to form the factorial $y!$ in the numerator,

\begin{equation}
\mathbb{E}[Y] = \sum^{\infty}_{ y=r } \frac{\color{red} y!}{ (r-1)! (y-r)!} p^r(1-p)^{y-r}.
\end{equation}

Next, we pull out the parameter $r$ from the summation,

\begin{equation}
\mathbb{E}[Y] = {\color{red} r } \sum^{\infty}_{y=r} \frac{y!}{{\color{red} r!} (y-r)!} p^r (1-p)^{y-r}.
\end{equation}

Next again, we pull out the parameter $1/p$ from the summation,

\begin{equation}
\mathbb{E}[Y] = \frac{r}{\color{red} p} \sum^{\infty}_{y=r} \frac{y!}{r! (y-r)!} p^{\color{red}r+1} (1-p)^{y-r}.
\end{equation}

Now, let $m-1=r$ in the summation,

\begin{equation}
\mathbb{E}[Y] = \frac rp \sum^{\infty}_{y={\color{red}m-1}} \frac{y!}{ {\color{red}(m-1)!} (y-{\color{red} m+1})!} p^m (1-p)^{y-{\color{red} m+1}}.
\end{equation}

And now, let $z-1 = y$ in the summation,

\begin{align}
\mathbb{E}[Y] = & \frac rp \sum^{\infty}_{\color{red}z=m} \frac{\color{red}(z-1)!}{(m-1)! {\color{red}(z-m)!}} p^m (1-p)^{\color{red}z-m} \\\\
              = & \frac rp \sum^{\infty}_{z=m} {z-1 \choose m-1} p^m (1-p)^{z-m} (\#eq:summation) \\\\
              = & \frac rp \cdot 1 \\\\
              = & \frac rp.
\end{align}

When you compare the summation in <strong>Eq.</strong> \@ref(eq:summation) to the summation in <strong>Eq.</strong> \@ref(eq:one), you see that they take the same form if you equate $z = y$ and $m = r$. This means that the summation in <strong>Eq.</strong> \@ref(eq:summation) reduces to 1,

In this manner, we are left with our final mean value,

::: { .highlight }
\begin{equation}
\mathbb{E}[Y] = \frac rp.
\end{equation}
:::
