---
title: 1. Field Axioms
author: ''
date: '2021-06-03'
slug: 1-field-axioms
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-06-03T06:44:24-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
math: true
type: book
graphic: true
jplayer: true
src_version: '212'
---
```{r setup, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
require(reticulate)
```

```{python, eval=TRUE, echo=FALSE, results="asis", warning=FALSE, message=FALSE}
sys.path.append('../../../assets/python')

from ctns_make  import ctns_make  as CTNS_MAKE
from ctns_build import ctns_build as CTNS_BUILD
import ctns_form as CTNS

VERSION=212
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
slide_list = [
    'axFieldS1'
  , 'axClosedS1'
  , 'axCommuteS1'
  , 'axAssocS1'
  , 'axDistS1'
  , 'axIdentS1'
  , 'axInverseS1'
]

m_list = [ { 'name': s, 'qset':[s] , 'options':CTNS.FORM_FLASHCARD_1 } for s in slide_list ]

q_list = [
    {'name': 'quiz_field_axioms', 'options':CTNS.FORM_QUIZ_1 + ["count=7"], 'qset': slide_list}
]
```

```{python, eval=FALSE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
for m in m_list:
    #CTNS_BUILD(target=m['qset'], id=m['name'], process_support_files=False, version=VERSION, write_image=False, image_target=m['name'], opt_ctns = m['options'], encrypt=False)
    CTNS_BUILD(target=m, process_support_files=False, version=VERSION, write_image=True, encrypt=False)
```

```{python, eval=TRUE, results="asis", echo=FALSE, warning=FALSE, message=FALSE}
for m in q_list:
    #CTNS_BUILD(target=m['qset'], id=m['name'], process_support_files=False, version=VERSION, write_image=False, image_target=m['name'], opt_ctns = m['options'], encrypt=False)
    CTNS_BUILD(target=m, process_support_files=False, version=VERSION, write_image=False, encrypt=False)
```

```{r eval=TRUE, echo=FALSE}
blogdown::shortcode('quiz_field_axioms')
```

Algebra today is built on a well-defined set of axioms from which all other algebraic properties are derived.

```{r eval=TRUE, echo=FALSE}
blogdown::shortcode('axFieldS1')
```

A set of numbers is a **Field** if it satisfies the following axioms for addition and multiplication.

- Closure
- Commutativity
- Associativity
- Distributivity
- Identity Elements
- Inverses

```{r eval=TRUE, echo=FALSE}
blogdown::shortcode('axClosedS1')
blogdown::shortcode('axCommuteS1')
blogdown::shortcode('axAssocS1')
blogdown::shortcode('axDistS1')
blogdown::shortcode('axIdentS1')
blogdown::shortcode('axInverseS1')
```
